version: '3.8'
services:
  react:
    container_name: spacex-app
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: spacex-app:dev
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
       - ./:/usr/src
       - /usr/src/node_modules